# DAT210x - Programming with Python for DS

## Module2 - Lab5

Barry Becker extrajo un subconjunto razonablemente limpio de la base de datos del censo estadounidense de 1994, con el objetivo de hacer predicciones para determinar si una persona hace más de 50 K al año. El conjunto de datos está alojado en la Universidad de California, el Depósito de Aprendizaje de Máquinas de Irvine, e incluye características como la edad, ocupación y horas trabajadas por semana de la persona, etc.

https://archive.ics.uci.edu/ml/datasets/Census+Income

Tan limpio como los datos, todavía no está listo para el análisis de SciKit-Learn! Utilizando lo que aprendió en este capítulo, limpie las distintas columnas codificándolas correctamente utilizando las mejores prácticas para que estén listas para ser examinadas. Hemos incluido un subconjunto de modificaciones del conjunto de datos en Module2 / Datasets / census.data y también tenemos algunos códigos iniciados para conseguir que vayas localizados en Module2 / assignment5.py.
"""
Barry Becker extracted a reasonably clean subset of the 1994, U.S. Census database, with a goal of running predictions to determine whether a person makes over 50K a year. The dataset is hosted on the University of California, Irvine's Machine Learning Repository and includes features such as the person's age, occupation, and hours worked per week, etc.

As clean as the data is, it still isn't quite ready for analysis by SciKit-Learn! Using what you've learned in this chapter, clean up the various columns by encode them properly using the best practices so that they're ready to be examined. We've included a modifies subset of the dataset at Module2/Datasets/census.data and also have some started code to get you going located at Module2/assignment5.py.

Import and alias Pandas:

In [1]:
import pandas as pd

As per usual, load up the specified dataset, setting appropriate header labels.

In [16]:
df = pd.read_csv('census.data')
df

,0,Bachelors,39,2174,White,0.1,40,Male,<=50K
0,1,Bachelors,50,?,White,0,13,Male,<=50K
1,2,HS-grad,38,?,White,0,40,Male,<=50K
2,3,11th,53,?,Black,0,40,Male,<=50K
3,4,Bachelors,28,0,Black,0,40,Female,<=50K
4,5,Masters,37,0,White,0,40,Female,<=50K
5,6,9th,49,0,Black,0,16,Female,<=50K
6,7,HS-grad,52,0,White,0,45,Male,>50K
7,8,Masters,31,14084,White,0,50,Female,>50K
8,9,Bachelors,42,5178,White,0,40,Male,>50K
9,10,Some-college,37,0,Black,0,80,Male,>50K
10,11,Bachelors,30,0,Asian-Pac-Islander,0,40,Male,>50K
11,12,Bachelors,23,0,White,0,30,Female,<=50K
12,13,7th-8th,34,0,Amer-Indian-Eskimo,0,45,Male,<=50K
13,14,HS-grad,25,0,White,0,35,Male,<=50K
14,15,HS-grad,32,0,White,0,40,Male,<=50K
15,16,11th,38,0,White,0,50,Male,<=50K
16,17,Masters,43,0,White,0,45,Female,>50K
17,18,Doctorate,40,0,White,0,60,Male,>50K
18,19,HS-grad,54,0,Black,0,20,Female,<=50K
19,20,9th,35,0,Black,0,40,Male,<=50K
20,21,11th,43,0,White,2042,40,Male,<=50K
21,22,HS-grad,59,0,White,0,40,Female,<=50K
22,23,Bachelors,56,0,White,0,40,Male,>50K
23,24,HS-grad,19,0,White,0,40,Male,<=50K
24,25,Some-college,54,0,Asian-Pac-Islander,0,60,Male,>50K
25,26,HS-grad,39,0,White,0,80,Male,<=50K
26,27,HS-grad,49,0,White,0,40,Male,<=50K
27,28,Some-college,20,0,Black,0,44,Male,<=50K
28,29,Bachelors,45,0,White,1408,40,Male,<=50K
29,30,Some-college,30,0,White,0,40,Male,<=50K
...,...,...,...,...,...,...,...,...,...
29505,29506,HS-grad,30,0,White,0,55,Male,<=50K
29506,29507,10th,32,0,White,0,40,Male,<=50K
29507,29508,Some-college,22,0,White,0,40,Male,<=50K
29508,29509,HS-grad,31,0,White,0,40,Female,<=50K
29509,29510,HS-grad,29,0,White,0,35,Female,<=50K
29510,29511,Bachelors,35,0,White,0,55,Female,>50K
29511,29512,Bachelors,30,0,Asian-Pac-Islander,0,99,Female,<=50K
29512,29513,Doctorate,34,0,White,0,60,Male,>50K
29513,29514,Bachelors,54,0,Asian-Pac-Islander,0,50,Male,>50K
29514,29515,Some-college,37,0,White,0,39,Female,<=50K
29515,29516,12th,22,0,Black,0,35,Male,<=50K
29516,29517,Bachelors,34,0,White,0,55,Female,>50K
29517,29518,HS-grad,30,0,Black,0,46,Male,<=50K
29518,29519,Bachelors,38,15020,Black,0,45,Female,>50K
29519,29520,Doctorate,71,0,White,0,10,Male,>50K
29520,29521,HS-grad,45,0,White,0,40,Female,<=50K
29521,29522,HS-grad,41,0,Black,0,32,Female,<=50K
29522,29523,HS-grad,72,0,White,0,25,Male,<=50K
29523,29524,Masters,31,0,Other,0,30,Female,<=50K
29524,29525,HS-grad,43,0,White,0,40,Male,<=50K
29525,29526,Some-college,43,0,White,0,40,Female,<=50K
29526,29527,Some-college,43,0,White,0,50,Male,<=50K
29527,29528,10th,32,0,Amer-Indian-Eskimo,0,40,Male,<=50K
29528,29529,Masters,32,0,Asian-Pac-Islander,0,11,Male,<=50K
29529,29530,Masters,53,0,White,0,40,Male,>50K
29530,29531,Some-college,22,0,White,0,40,Male,<=50K
29531,29532,HS-grad,40,0,White,0,40,Male,>50K
29532,29533,HS-grad,58,0,White,0,40,Female,<=50K
29533,29534,HS-grad,22,0,White,0,20,Male,<=50K
29534,29535,HS-grad,52,15024,White,0,40,Female,>50K

In [17]:
del df['0'] # Borramos la primera columna 
df

          Bachelors  39   2174               White   0.1  40    Male  <=50K
0         Bachelors  50      ?               White     0  13    Male  <=50K
1           HS-grad  38      ?               White     0  40    Male  <=50K
2              11th  53      ?               Black     0  40    Male  <=50K
3         Bachelors  28      0               Black     0  40  Female  <=50K
4           Masters  37      0               White     0  40  Female  <=50K
5               9th  49      0               Black     0  16  Female  <=50K
6           HS-grad  52      0               White     0  45    Male   >50K
7           Masters  31  14084               White     0  50  Female   >50K
8         Bachelors  42   5178               White     0  40    Male   >50K
9      Some-college  37      0               Black     0  80    Male   >50K
10        Bachelors  30      0  Asian-Pac-Islander     0  40    Male   >50K
11        Bachelors  23      0               White     0  30  Female  <=50K
12          7th-8th  34      0  Amer-Indian-Eskimo     0  45    Male  <=50K
13          HS-grad  25      0               White     0  35    Male  <=50K
14          HS-grad  32      0               White     0  40    Male  <=50K
15             11th  38      0               White     0  50    Male  <=50K
16          Masters  43      0               White     0  45  Female   >50K
17        Doctorate  40      0               White     0  60    Male   >50K
18          HS-grad  54      0               Black     0  20  Female  <=50K
19              9th  35      0               Black     0  40    Male  <=50K
20             11th  43      0               White  2042  40    Male  <=50K
21          HS-grad  59      0               White     0  40  Female  <=50K
22        Bachelors  56      0               White     0  40    Male   >50K
23          HS-grad  19      0               White     0  40    Male  <=50K
24     Some-college  54      0  Asian-Pac-Islander     0  60    Male   >50K
25          HS-grad  39      0               White     0  80    Male  <=50K
26          HS-grad  49      0               White     0  40    Male  <=50K
27     Some-college  20      0               Black     0  44    Male  <=50K
28        Bachelors  45      0               White  1408  40    Male  <=50K
29     Some-college  30      0               White     0  40    Male  <=50K
...             ...  ..    ...                 ...   ...  ..     ...    ...
29505       HS-grad  30      0               White     0  55    Male  <=50K
29506          10th  32      0               White     0  40    Male  <=50K
29507  Some-college  22      0               White     0  40    Male  <=50K
29508       HS-grad  31      0               White     0  40  Female  <=50K
29509       HS-grad  29      0               White     0  35  Female  <=50K
29510     Bachelors  35      0               White     0  55  Female   >50K
29511     Bachelors  30      0  Asian-Pac-Islander     0  99  Female  <=50K
29512     Doctorate  34      0               White     0  60    Male   >50K
29513     Bachelors  54      0  Asian-Pac-Islander     0  50    Male   >50K
29514  Some-college  37      0               White     0  39  Female  <=50K
29515          12th  22      0               Black     0  35    Male  <=50K
29516     Bachelors  34      0               White     0  55  Female   >50K
29517       HS-grad  30      0               Black     0  46    Male  <=50K
29518     Bachelors  38  15020               Black     0  45  Female   >50K
29519     Doctorate  71      0               White     0  10    Male   >50K
29520       HS-grad  45      0               White     0  40  Female  <=50K
29521       HS-grad  41      0               Black     0  32  Female  <=50K
29522       HS-grad  72      0               White     0  25    Male  <=50K
29523       Masters  31      0               Other     0  30  Female  <=50K
29524       HS-grad  43      0               White     0  40    Male  <=50K
29525  Some-college  43      0               White     0  40  Female  <=50K
29526  Some-college  43      0               White     0  50    Male  <=50K
29527          10th  32      0  Amer-Indian-Eskimo     0  40    Male  <=50K
29528       Masters  32      0  Asian-Pac-Islander     0  11    Male  <=50K
29529       Masters  53      0               White     0  40    Male   >50K
29530  Some-college  22      0               White     0  40    Male  <=50K
29531       HS-grad  40      0               White     0  40    Male   >50K
29532       HS-grad  58      0               White     0  40  Female  <=50K
29533       HS-grad  22      0               White     0  20    Male  <=50K
29534       HS-grad  52  15024               White     0  40  Female   >50K

[29535 rows x 8 columns]

In [21]:
df.columns = ['education', 'age', 'capitalgain', 'race', 'capitalloss', 'hours-per-week', 'sex', 'classification']
df

,education,age,capitalgain,race,capitalloss,hours-per-week,sex,classification
0,Bachelors,50,?,White,0,13,Male,<=50K
1,HS-grad,38,?,White,0,40,Male,<=50K
2,11th,53,?,Black,0,40,Male,<=50K
3,Bachelors,28,0,Black,0,40,Female,<=50K
4,Masters,37,0,White,0,40,Female,<=50K
5,9th,49,0,Black,0,16,Female,<=50K
6,HS-grad,52,0,White,0,45,Male,>50K
7,Masters,31,14084,White,0,50,Female,>50K
8,Bachelors,42,5178,White,0,40,Male,>50K
9,Some-college,37,0,Black,0,80,Male,>50K
10,Bachelors,30,0,Asian-Pac-Islander,0,40,Male,>50K
11,Bachelors,23,0,White,0,30,Female,<=50K
12,7th-8th,34,0,Amer-Indian-Eskimo,0,45,Male,<=50K
13,HS-grad,25,0,White,0,35,Male,<=50K
14,HS-grad,32,0,White,0,40,Male,<=50K
15,11th,38,0,White,0,50,Male,<=50K
16,Masters,43,0,White,0,45,Female,>50K
17,Doctorate,40,0,White,0,60,Male,>50K
18,HS-grad,54,0,Black,0,20,Female,<=50K
19,9th,35,0,Black,0,40,Male,<=50K
20,11th,43,0,White,2042,40,Male,<=50K
21,HS-grad,59,0,White,0,40,Female,<=50K
22,Bachelors,56,0,White,0,40,Male,>50K
23,HS-grad,19,0,White,0,40,Male,<=50K
24,Some-college,54,0,Asian-Pac-Islander,0,60,Male,>50K
25,HS-grad,39,0,White,0,80,Male,<=50K
26,HS-grad,49,0,White,0,40,Male,<=50K
27,Some-college,20,0,Black,0,44,Male,<=50K
28,Bachelors,45,0,White,1408,40,Male,<=50K
29,Some-college,30,0,White,0,40,Male,<=50K
...,...,...,...,...,...,...,...,...
29505,HS-grad,30,0,White,0,55,Male,<=50K
29506,10th,32,0,White,0,40,Male,<=50K
29507,Some-college,22,0,White,0,40,Male,<=50K
29508,HS-grad,31,0,White,0,40,Female,<=50K
29509,HS-grad,29,0,White,0,35,Female,<=50K
29510,Bachelors,35,0,White,0,55,Female,>50K
29511,Bachelors,30,0,Asian-Pac-Islander,0,99,Female,<=50K
29512,Doctorate,34,0,White,0,60,Male,>50K
29513,Bachelors,54,0,Asian-Pac-Islander,0,50,Male,>50K
29514,Some-college,37,0,White,0,39,Female,<=50K
29515,12th,22,0,Black,0,35,Male,<=50K
29516,Bachelors,34,0,White,0,55,Female,>50K
29517,HS-grad,30,0,Black,0,46,Male,<=50K
29518,Bachelors,38,15020,Black,0,45,Female,>50K
29519,Doctorate,71,0,White,0,10,Male,>50K
29520,HS-grad,45,0,White,0,40,Female,<=50K
29521,HS-grad,41,0,Black,0,32,Female,<=50K
29522,HS-grad,72,0,White,0,25,Male,<=50K
29523,Masters,31,0,Other,0,30,Female,<=50K
29524,HS-grad,43,0,White,0,40,Male,<=50K
29525,Some-college,43,0,White,0,40,Female,<=50K
29526,Some-college,43,0,White,0,50,Male,<=50K
29527,10th,32,0,Amer-Indian-Eskimo,0,40,Male,<=50K
29528,Masters,32,0,Asian-Pac-Islander,0,11,Male,<=50K
29529,Masters,53,0,White,0,40,Male,>50K
29530,Some-college,22,0,White,0,40,Male,<=50K
29531,HS-grad,40,0,White,0,40,Male,>50K
29532,HS-grad,58,0,White,0,40,Female,<=50K
29533,HS-grad,22,0,White,0,20,Male,<=50K
29534,HS-grad,52,15024,White,0,40,Female,>50K

Excellent.

Now, use basic pandas commands to look through the dataset. Get a feel for it before proceeding!

Do the data-types of each column reflect the values you see when you look through the data using a text editor / spread sheet program? If you see `object` where you expect to see `int32` or `float64`, that is a good indicator that there might be a string or missing value or erroneous value in the column.

""" 

Excelente.
Ahora, use comandos básicos de pandas para examinar el conjunto de datos. Consiga una sensación para él antes de proceder!
¿Los tipos de datos de cada columna reflejan los valores que se ven al examinar los datos mediante un programa de editor de texto / hoja de cálculo? Si ve el objeto donde espera ver int32 o float64, es un buen indicador de que puede haber una cadena o valor faltante o valor erróneo en la columna.

In [22]:
df.dtypes

education         object
age                int64
capitalgain       object
race              object
capitalloss        int64
hours-per-week     int64
sex               object
classification    object
dtype: object

In [23]:
df.capitalgain = pd.to_numeric (df.capitalgain, errors ='coerce')

df.dtypes

education          object
age                 int64
capitalgain       float64
race               object
capitalloss         int64
hours-per-week      int64
sex                object
classification     object
dtype: object

In [33]:
df

,education,age,capitalgain,race,capitalloss,hours-per-week,sex,classification
0,Bachelors,50,NaN,White,0,13,Male,<=50K
1,HS-grad,38,NaN,White,0,40,Male,<=50K
2,11th,53,NaN,Black,0,40,Male,<=50K
3,Bachelors,28,0.0,Black,0,40,Female,<=50K
4,Masters,37,0.0,White,0,40,Female,<=50K
5,9th,49,0.0,Black,0,16,Female,<=50K
6,HS-grad,52,0.0,White,0,45,Male,>50K
7,Masters,31,14084.0,White,0,50,Female,>50K
8,Bachelors,42,5178.0,White,0,40,Male,>50K
9,Some-college,37,0.0,Black,0,80,Male,>50K
10,Bachelors,30,0.0,Asian-Pac-Islander,0,40,Male,>50K
11,Bachelors,23,0.0,White,0,30,Female,<=50K
12,7th-8th,34,0.0,Amer-Indian-Eskimo,0,45,Male,<=50K
13,HS-grad,25,0.0,White,0,35,Male,<=50K
14,HS-grad,32,0.0,White,0,40,Male,<=50K
15,11th,38,0.0,White,0,50,Male,<=50K
16,Masters,43,0.0,White,0,45,Female,>50K
17,Doctorate,40,0.0,White,0,60,Male,>50K
18,HS-grad,54,0.0,Black,0,20,Female,<=50K
19,9th,35,0.0,Black,0,40,Male,<=50K
20,11th,43,0.0,White,2042,40,Male,<=50K
21,HS-grad,59,0.0,White,0,40,Female,<=50K
22,Bachelors,56,0.0,White,0,40,Male,>50K
23,HS-grad,19,0.0,White,0,40,Male,<=50K
24,Some-college,54,0.0,Asian-Pac-Islander,0,60,Male,>50K
25,HS-grad,39,0.0,White,0,80,Male,<=50K
26,HS-grad,49,0.0,White,0,40,Male,<=50K
27,Some-college,20,0.0,Black,0,44,Male,<=50K
28,Bachelors,45,0.0,White,1408,40,Male,<=50K
29,Some-college,30,0.0,White,0,40,Male,<=50K
...,...,...,...,...,...,...,...,...
29505,HS-grad,30,0.0,White,0,55,Male,<=50K
29506,10th,32,0.0,White,0,40,Male,<=50K
29507,Some-college,22,0.0,White,0,40,Male,<=50K
29508,HS-grad,31,0.0,White,0,40,Female,<=50K
29509,HS-grad,29,0.0,White,0,35,Female,<=50K
29510,Bachelors,35,0.0,White,0,55,Female,>50K
29511,Bachelors,30,0.0,Asian-Pac-Islander,0,99,Female,<=50K
29512,Doctorate,34,0.0,White,0,60,Male,>50K
29513,Bachelors,54,0.0,Asian-Pac-Islander,0,50,Male,>50K
29514,Some-college,37,0.0,White,0,39,Female,<=50K
29515,12th,22,0.0,Black,0,35,Male,<=50K
29516,Bachelors,34,0.0,White,0,55,Female,>50K
29517,HS-grad,30,0.0,Black,0,46,Male,<=50K
29518,Bachelors,38,15020.0,Black,0,45,Female,>50K
29519,Doctorate,71,0.0,White,0,10,Male,>50K
29520,HS-grad,45,0.0,White,0,40,Female,<=50K
29521,HS-grad,41,0.0,Black,0,32,Female,<=50K
29522,HS-grad,72,0.0,White,0,25,Male,<=50K
29523,Masters,31,0.0,Other,0,30,Female,<=50K
29524,HS-grad,43,0.0,White,0,40,Male,<=50K
29525,Some-college,43,0.0,White,0,40,Female,<=50K
29526,Some-college,43,0.0,White,0,50,Male,<=50K
29527,10th,32,0.0,Amer-Indian-Eskimo,0,40,Male,<=50K
29528,Masters,32,0.0,Asian-Pac-Islander,0,11,Male,<=50K
29529,Masters,53,0.0,White,0,40,Male,>50K
29530,Some-college,22,0.0,White,0,40,Male,<=50K
29531,HS-grad,40,0.0,White,0,40,Male,>50K
29532,HS-grad,58,0.0,White,0,40,Female,<=50K
29533,HS-grad,22,0.0,White,0,20,Male,<=50K
29534,HS-grad,52,15024.0,White,0,40,Female,>50K

Try use `your_data_frame['your_column'].unique()` or equally, `your_data_frame.your_column.unique()` to see the unique values of each column and identify the rogue values.

If you find any value that should be properly encoded to NaNs, you can convert them either using the `na_values` parameter when loading the dataframe. Or alternatively, use one of the other methods discussed in the reading.

"""""

Intente usar su_data_frame ['your_column']. Unique () o igualmente, your_data_frame.your_column.unique () para ver los valores únicos de cada columna e identificar los valores deshonestos.
Si encuentra algún valor que debería estar correctamente codificado en NaNs, puede convertirlos utilizando el parámetro na_values ​​al cargar el marco de datos. O alternativamente, utilice uno de los otros métodos discutidos en la lectura.

In [26]:
df.education.unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       '7th-8th', 'Doctorate', '5th-6th', '10th', '1st-4th', 'Preschool',
       '12th'], dtype=object)

In [27]:
df.age.unique()

array([50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 34, 25, 32, 43, 40, 54,
       35, 59, 56, 19, 39, 20, 45, 22, 48, 21, 24, 57, 44, 18, 47, 46, 41,
       29, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 51, 58, 26,
       60, 90, 66, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 75, 82, 83,
       84, 85, 88, 86, 87], dtype=int64)

In [28]:
df.capitalgain.unique()

array([    nan,      0.,  14084.,   5178.,   5013.,   2407.,  14344.,
        15024.,   7688.,  34095.,   4064.,   4386.,   7298.,   1409.,
         3674.,   1055.,   3464.,   2050.,   2176.,   2174.,    594.,
         6849.,   4101.,   1111.,   3411.,   2597.,  25236.,   4650.,
         9386.,   2463.,   3103.,  10605.,   2964.,   3325.,   2580.,
         3471.,   4865.,   6514.,   1471.,   2329.,  99999.,  20051.,
         2105.,   2885.,  25124.,  10520.,   2202.,   2961.,  27828.,
         6767.,   8614.,   2228.,   1506.,  13550.,   2635.,   5556.,
         4787.,   3781.,   3137.,   3818.,   3942.,    914.,    401.,
         2829.,   2977.,   4934.,   2062.,  15020.,   1424.,   3273.,
        22040.,   4416.,  10566.,    991.,   4931.,   1086.,   7430.,
         6497.,    114.,   7896.,   2346.,   3432.,   2907.,   1151.,
         2414.,   2290.,   3418.,  15831.,  41310.,   4508.,   5455.,
         2538.,   3456.,   3908.,   1848.,   3887.,   5721.,   9562.,
         6418.,   1455.,   2036.,   1831.,  11678.,   2936.,   2993.,
         7443.,   6360.,   2354.,   1797.,   1173.,   4687.,   2009.,
         6097.,   2653.,  18481.,   7978.,   2387.,   6723.,   5060.])

In [29]:
df.race.unique()

array(['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo',
       'Other'], dtype=object)

In [30]:
df.capitalloss.unique()

array([   0, 2042, 1408, 1573, 1902, 1887, 1719, 1762, 2179, 1816, 1980,
       1977, 1876, 1340, 2206, 1741, 1485, 1564, 2339, 2415, 1721, 1380,
       2051, 2352, 1672,  653, 2392, 1504, 2001, 1590, 1651, 1628, 1848,
       1740, 2002, 1579, 2258, 1669, 1602,  419, 2547, 2174, 2205, 1138,
       2238,  625, 2377,  213, 1539,  880, 1092, 1594, 3004, 2231, 1844,
        810, 2559, 2057, 1974,  974, 1825, 1735, 1258, 2129, 2603, 2282,
        323, 4356, 2444, 2246, 2149, 1617, 1648, 2824, 2489, 3770, 1755,
       3683, 1668, 1726, 2267, 2457,  155, 3900, 2201, 1944, 2467, 2163,
       2754, 2472, 1411], dtype=int64)

Lastly, print out your dataframe!

In [31]:
# df.hours-per-weekk.unique()
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [32]:
df.classification.unique()

array(['<=50K', '>50K'], dtype=object)

Look through your data and identify any potential categorical features. Ensure you properly encode any ordinal and nominal types using the methods discussed in the chapter.
Be careful! Some features can be represented as either categorical or continuous (numerical). If you ever get confused, think to yourself what makes more sense generally---to represent such features with a continuous numeric type... or a series of categories?

"""
Mire a través de sus datos e identifique cualquier característica categórica potencial. Asegúrese de codificar correctamente cualquier tipo ordinal y nominal usando los métodos discutidos en el capítulo.
¡Ten cuidado! Algunas características pueden ser representadas como categóricas o continuas (numéricas). Si alguna vez te confundes, piensa en ti mismo lo que hace más sentido generalmente --- representar tales características con un tipo numérico continuo ... o una serie de categorías?

In [ ]:
# .. your code here ..

Lastly, print out your dataframe!